---

version: '3'
services: 
  solr: 
    image: solr:latest 
    container_name: solr
    volumes: 
      - solrdata:/var/solr/:rw
    ports: 
      - 8983:8983
    command:
      - solr-precreate
      - logs
    

  fluentd: 
    build: ./fluentd 
    volumes: 
      - ./fluentd/fluentd.conf:/fluentd/fluentd.conf:ro
    ports: 
      - 5514:5514/udp
      - 8888:8888

  grafana: 
    image: grafana/grafana:latest 
    ports: 
      - 3000:3000
    environment: 
      - "GF_INSTALL_PLUGINS=pue-solr-datasource"

  banana: 
    image: aaadel/banana
    ports: 
      - 9901:9901
    volumes: 
      - ./banana/config.json:/opt/banana/config.json:ro

volumes: 
  solrdata: 
